InfotechLab.Web/Models/HeaderViewModel.cs
using InfotechLab.Entities;
using System.Diagnostics.Metrics;

namespace InfotechLab.Web.Models
{
	public class HeaderViewModel
    {
        public IList<City> Cities { get; set; }
        public IList<County> Counties { get; set; }
        public IList<Category> Categories { get; set; }
        public SearchExpertServiceViewModel SearchExpertService { get; set; }
    }
}

InfotechLab.Web/Controllers/AuthenticationController.cs
using InfotechLab.Business.Helpers;
using InfotechLab.Business.Services.Abstract;
using InfotechLab.Entities;
using InfotechLab.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace InfotechLab.Web.Controllers
{
	public class AuthenticationController : Controller
	{
		private ILoginService _loginService;
		private ICategoryService _categoryService;
		private ICookieHelper _cookieHelper;
		public AuthenticationController(ILoginService loginService, ICookieHelper cookieHelper, ICategoryService categoryService)
		{
			_loginService = loginService;
			_cookieHelper = cookieHelper;
			_categoryService = categoryService;
		}

		public IActionResult Login()
		{
			var cookie = _cookieHelper.Read(CookieTypes.User, Request);
			if (!string.IsNullOrEmpty(cookie))
			{

			}
			return View();
		}
		public IActionResult Register()
		{
			RegisterViewModel viewModel = new RegisterViewModel();
			viewModel.Categories = _categoryService.GetAll();
			return View(viewModel);
		}
		[HttpPost]
		public IActionResult Login(LoginViewModel model)
		{
			if (ModelState.IsValid)
			{
					var loginResult = _loginService.UserLogin(model.Email, model.Password, Response);
					return RedirectToAction("Index", "Home");
			}

			else
			{
				return View(model);
			}
		}

		[HttpPost]
		public IActionResult Register(RegisterViewModel model)
		
		{
			if (ModelState.IsValid)
			{
				var modelUser = new User()
				{
					FirstName = model.FirstName,
					LastName = model.LastName,
					Email = model.Email,
					Password = model.Password,
					IsActive = true,
					CreatedDate = DateTime.Now,
					BirthOfDate = model.BirthOfDate,
					IsExpert = model.IsExpert,
					Description = model.Description,
					Address = model.Address,

					CountyId = model.CountyId,

					
					
				};
				var user = _loginService.Register(modelUser, Response);
				if (user != null)
				{
					//hizmet alan sayfasına gitsin
					return RedirectToAction("Index", "Home");
				}
			}

			return View(model);
		}

		public IActionResult Exit()
		{
			bool result = _loginService.Exit(Request);
			if (result)
			{
				return RedirectToAction("Index", "Home");
			}
			else
			{
				return RedirectToAction("Error", "Home");
			}
			return View();
		}		
		public IActionResult LoginRequired()
		{
			return View();
		}
	}
}

InfotechLab.Web/ViewComponents/SearchExpertServiceViewComponent.cs
using InfotechLab.Entities;
using InfotechLab.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace InfotechLab.Web.ViewComponents
{
	public class SearchExpertServiceViewComponent : ViewComponent
	{
		public SearchExpertServiceViewComponent()
		{
			
		}
		public ViewViewComponentResult Invoke()
		{
			return View(new SearchExpertServiceViewModel());
		}
	}
}

InfotechLab.Web/Views/Shared/Components/Header/Default.cshtml
	<!-- header-start -->
<header>
	<div id="header-sticky" class="main-header">
		<div class="container-fluid header-container-p">
			<div class="row align-items-center">
				<div class="col-lg-3 col-md-6">
					@Html.ActionLink("AnaSayfa", "Index", "Home", null, new { @class = "btn" })
				</div>
				<div class="col-lg-9 col-md-6 d-none d-md-block">
					<div class="menu-area">
						<div class="header-btn">
							@if (string.IsNullOrEmpty(ViewBag.Name))
							{
								@Html.ActionLink("Giriş Yap", "Login", "Authentication", null, new { @class = "btn mr-2" })
								@Html.ActionLink("Kayıt Ol", "Register", "Authentication", null, new { @class = "btn red-btn" })
							}
							else
							{
								<div>@ViewBag.Name</div>
								@if (@ViewBag.IsExpert)
								{
									@Html.ActionLink("Hizmet Taleplerim", "ExpertBids", "UserProfile", null, new { @class = "btn" })
								}
								else
								{
									@Html.ActionLink("Hizmet Taleplerim", "UserBids", "UserProfile", null, new { @class = "btn" })
								}
								@Html.ActionLink("Profil", "Index", "UserProfile", new {userId = ViewBag.UserId}, new { @class = "btn mr-2" })
								@Html.ActionLink("Çıkış", "Exit", "Authentication", null, new { @class = "btn red-btn" })
							}
							<a href="#" class="btn ml-5" data-toggle="modal" data-target="#exampleModalLong"><img src="/img/icon/calculator-symbols.png" alt="icon">Hizmet için İl/İlçe Seç</a>

						</div>
					</div>
				</div>
			</div>
			<!-- Modal -->
			@await Component.InvokeAsync("SearchExpertService")
		</div>
	</div>
</header>

<!-- header-start-end -->