InfotechLab.Web/ViewComponents/HeaderViewComponent.cs
using InfotechLab.Business.ComponentHandler;
using InfotechLab.Business.Services.Abstract;
using InfotechLab.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace InfotechLab.Web.ViewComponents
{
	public class HeaderViewComponent :ViewComponent
	{
		private readonly IUserService _userService;

		public HeaderViewComponent(IUserService userService)
		{
			_userService = userService;
		}

		public ViewViewComponentResult Invoke()
		{
			var result = _userService.GetUserData(Request);
			if (result != null)
			{
				if (string.IsNullOrEmpty(result.LoginGuidKey))
				{
                    return View();
                }

                ViewBag.Name = result?.FirstName + " " + result?.LastName;
				ViewBag.IsExpert = result?.IsExpert;
				ViewBag.UserId = result?.Id;
			}
			return View();
		}
	}
}

InfotechLab.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>Transprk - Cargo, Logistics & Transport HTML5 Template</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
	<!-- Place favicon.ico in the root directory -->
	<!-- CSS here -->
	<link rel="stylesheet" href="/css/bootstrap.min.css">
	<link rel="stylesheet" href="/css/animate.min.css">
	<link rel="stylesheet" href="/css/magnific-popup.css">
	<link rel="stylesheet" href="/css/fontawesome-all.min.css">
	<link rel="stylesheet" href="/css/aos.css">
	<link rel="stylesheet" href="/css/nice-select.css">
	<link rel="stylesheet" href="/css/flaticon.css">
	<link rel="stylesheet" href="/css/meanmenu.css">
	<link rel="stylesheet" href="/css/slick.css">
	<link rel="stylesheet" href="/css/default.css">
	<link rel="stylesheet" href="/css/style.css">
	<link rel="stylesheet" href="/css/responsive.css">
	<!-- JS here -->
	<script src="/js/vendor/jquery-1.12.4.min.js"></script>
	<script src="/js/popper.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
	<script src="/js/isotope.pkgd.min.js"></script>
	<script src="/js/slick.min.js"></script>
	<script src="/js/jquery.meanmenu.min.js"></script>
	<script src="/js/ajax-form.js"></script>
	<script src="/js/wow.min.js"></script>
	<script src="/js/aos.js"></script>
	<script src="/js/paroller.js"></script>
	<script src="/js/jquery.waypoints.min.js"></script>
	<script src="/js/jquery.counterup.min.js"></script>
	<script src="/js/jquery.nice-select.min.js"></script>
	<script src="/js/jquery.scrollUp.min.js"></script>
	<script src="/js/imagesloaded.pkgd.min.js"></script>
	<script src="/js/jquery.magnific-popup.min.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCo_pcAdFNbTDCAvMwAD19oRTuEmb9M50c"></script>
	<script src="/js/plugins.js"></script>
	<script src="/js/main.js"></script>
</head>
<body>

@await Component.InvokeAsync("Header")
@RenderBody()

</body>
</html>