InfotechLab.Web/Controllers/CategoryListController.cs
using InfotechLab.Business.Services.Abstract;
using InfotechLab.Business.Services.Concrete;
using InfotechLab.Entities;
using InfotechLab.Web.Models;
using InfotechLab.Web.ViewComponents;
using Microsoft.AspNetCore.Mvc;

namespace InfotechLab.Web.Controllers
{
	public class CategoryListController : Controller
	{
		private readonly IUserService _userService;
		ICategoryService _categoryService;
		ICityService _cityService;
		ICountyService _countyService;
		IUserCategoryService _userCategoryService;
		private IBidService _bidService;

		public CategoryListController(ICategoryService categoryService, ICityService cityService, ICountyService countyService, IUserService userService, IUserCategoryService userCategoryService, IBidService bidService)
		{
			_categoryService = categoryService;
			_cityService = cityService;
			_countyService = countyService;
			_userService = userService;
			_userCategoryService = userCategoryService;
			_bidService = bidService;
		}
		public IActionResult Index(int Id)
		{
			var user = _userService.GetUserData(Request);
			if (user is null)
			{
				return RedirectToAction("Login", "Authentication");
			}
			var result = _userService.GetUsersInSelectedCategoryAndCounty(Id, user.CountyId);
			ViewData["CategoryId"] = Id;
			return View(result);
		}
		public IActionResult GetUserCityCountyAndCategoryId()
		{
			var user = _userService.GetUserData(Request);
			var cityId = _countyService.Get(x => x.Id == user.CountyId).CityId;
			var categoryIds = _userCategoryService.GetAll(x => x.UserId == user.Id).Select(x => x.CategoryId).ToArray();

			return Json(new { userId = user.Id, countyId = user.CountyId, cityId = cityId, categoryIds = categoryIds });
		}
		public IActionResult GetCities()
		{
			return Json(_cityService.GetAll());
		}
		public IActionResult GetCounties(int cityId)
		{
			return Json(_countyService.GetAll(x => x.CityId == cityId));
		}
		public IActionResult GetCategories()
		{
			return Json(_categoryService.GetAll());
		}
		
		[HttpPost]
		public IActionResult SearchExpertService(SearchExpertServiceViewModel model)
		{
			var user = _userService.GetUserData(Request);
			if (user is null)
			{
				return RedirectToAction("Login", "Authentication");
			}
			else
			{
				var result = _userService.GetUsersInSelectedCategoryAndCounty(model.CategoryId, model.CountyId);
				ViewData["CategoryId"] = model.CategoryId;
				return View("Index", result);
			}
		}

		public IActionResult CreateBid(int expertId, int categoryId)
		{
			var user = _userService.GetUserData(Request);
			var userCategory = _userCategoryService.Get(x => x.UserId == expertId && x.CategoryId == categoryId);
			Bid model = new Bid
			{
				UserCategoryId = userCategory.Id,
				UserId = user.Id
			};
			return View(model);
		}

		[HttpPost]
		public IActionResult CreateBid(Bid model)
		{
			var user = _userService.GetUserData(Request);
			_bidService.Add(new Bid
			{
				CreatedDate = DateTime.Now,
				UserCategoryId = model.UserCategoryId,
				UserId = user.Id,
				IsAccepted = false,
				Description = model.Description,
			});
			return RedirectToAction("UserBids", "UserProfile");
		}
		public IActionResult ExpertCreateBid(int bidId)
		{
			var expert = _userService.GetUserData(Request);
			var bid = _bidService.Get(x => x.Id == bidId);
			return View(bid);
		}
		[HttpPost]
		public IActionResult ExpertCreateBid(Bid model)
		{
			var user = _userService.GetUserData(Request);
			var bid = _bidService.Get(x => x.Id == model.Id);
			bid.Price = model.Price;
			bid.FinishDate = model.FinishDate;
			_bidService.Update(bid);
			return RedirectToAction("ExpertBids", "UserProfile");
		}
		public IActionResult AcceptBid(int id)
		{
			var bid = _bidService.Get(x => x.Id == id);
			bid.IsAccepted = true;
			_bidService.Update(bid);
			return RedirectToAction("UserBids", "UserProfile");
		}
	}
}

InfotechLab.Web/Controllers/UserProfileController.cs
using InfotechLab.Business.Services.Abstract;
using InfotechLab.Entities;
using InfotechLab.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace InfotechLab.Web.Controllers
{
	public class UserProfileController : Controller
	{
		private ICategoryService _categoryService;
		private IUserService _userService;
		private IUserCategoryService _userCategoryService;
		private IBidService _bidService;


		public UserProfileController(ICategoryService categoryService, IUserService userService, IUserCategoryService userCategoryService, IBidService bidService)
		{
			_categoryService = categoryService;
			_userService = userService;
			_userCategoryService = userCategoryService;
			_bidService = bidService;
		}

		public IActionResult Index()
		{
			return View();
		}

		[HttpGet]
		public IActionResult Index(int userId)
		{
			var userProfile = _userService.GetIncluded(x => x.Id == userId);
			var userModel = new UserModel
			{
				FirstName = userProfile.FirstName,
				LastName = userProfile.LastName,
				Email = userProfile.Email,
				BirthOfDate = userProfile.BirthOfDate,
				Address = userProfile.Address,
				Description = userProfile.Description,
				PhoneNumber = userProfile.PhoneNumber,
				Categories = _categoryService.GetAll(),
				CategoryIds = userProfile.UserCategories.Select(c => c.Id).ToArray(),
				CreatedDate = userProfile.CreatedDate,
				Id = userProfile.Id,
				IsActive = userProfile.IsActive,
				IsExpert = userProfile.IsExpert,
				LoginGuidKey = userProfile.LoginGuidKey,
				CountyId = userProfile.CountyId,
				CityId = userProfile.County.CityId,
			};
			return View(userModel);
		}
		[HttpPost]
		public IActionResult Index(UserModel userProfile)
		{
			if (userProfile.CityId == 0 || userProfile.CountyId == 0 || userProfile.IsExpert && (userProfile.CategoryIds is null || userProfile.CategoryIds.Length == 0))
			{
				ViewBag.Error = " Lütfen bilgileri kontrol ediniz!";
				return RedirectToAction("Index", "UserProfile", new { userId = userProfile.Id });
			}
			var countyId = _userService.Get(x => x.Id == userProfile.Id);
			var user = _userService.Get(x => x.Id == userProfile.Id);
			user.FirstName = userProfile.FirstName;
			user.LastName = userProfile.LastName;
			user.Email = userProfile.Email;
			user.BirthOfDate = userProfile.BirthOfDate;
			user.Address = userProfile.Address;
			user.Description = userProfile.Description;
			user.PhoneNumber = userProfile.PhoneNumber;
			user.IsExpert = userProfile.IsExpert;
			user.CountyId = userProfile.CountyId;
			user.UserCategories = null;
			user.County = null;

			_userService.Update(user);
			if (userProfile.IsExpert)
			{
				foreach (var categoryId in userProfile.CategoryIds)
				{
					_userCategoryService.DeleteAllUserCategoriesByUserId(userProfile.Id);
				}
				foreach (var categoryId in userProfile.CategoryIds)
				{
					_userCategoryService.Add(new UserCategory { CategoryId = categoryId, UserId = user.Id, CountyId = user.CountyId });
				}
			}
			return RedirectToAction("Index", "UserProfile",new {userId = user.Id});
		}


		public IActionResult UserBids()
		{
			var user = _userService.GetUserData(Request);
			var bids = _bidService.GetAll(x => x.UserId == user.Id);
			return View(bids);
		}	
		
		public IActionResult ExpertBids()
		{
			var user = _userService.GetUserData(Request);
			var bids = _bidService.GetAllBidsByUserCategory(x => x.UserCategory.UserId == user.Id);
			return View(bids);
		}
	}
}

InfotechLab.Web/Views/UserProfile/ExpertBids.cshtml
@using InfotechLab.Entities;
@model IList<InfotechLab.Entities.Bid>
@{
	Layout = "_Layout";
}
<div class="col-lg-4 order-2 order-lg-0">
	<aside class="blog-sidebar">
		<div class="widget mb-40">
			<div class="single-sidebar white-bg">
				<div class="sidebar-title mb-25">
					<h3>Teklifler</h3>
				</div>
				<div class="cat-list">
					<ul>
						@foreach (var item in Model)
						{
							<li>
								<div class="row justify-content-center">
									<div class="col-md-6">
										@item.CreatedDate
									</div>
									@if (item.Price is not null)
									{
										<div class="col-md-6">
											@item.Price
										</div>
									}

								</div>
								<div class="row justify-content-center">
									<div class="col">
										@item.Description
									</div>
								</div>

								<div class="row justify-content-center">
									<div class="col-md-6">
										@Html.ActionLink("Teklif Ver","ExpertCreateBid","CategoryList",new {bidId = item.Id},new{@class = "btn red-btn"})
									</div>
								</div>
							</li>
						}
					</ul>
				</div>
			</div>
		</div>
	</aside>
</div>

InfotechLab.Web/Views/UserProfile/Index.cshtml
@{
	Layout = "_Layout";
}
@model UserModel
<!-- main-area -->
<main>

	<!-- support-area -->
	<div class="support-area support-bg pt-110 pb-120">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-xl-7 col-lg-10">
					<div class="s-section-title text-center mb-60">
						<h2>PROFİL</h2>
					</div>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-lg-10">
					<div class="support-form text-center">
						@if (!String.IsNullOrEmpty(ViewBag.Error))
						{
							<div style="color:red">@ViewBag.Error</div>
						}
						<form asp-controller="UserProfile" asp-action="Index" method="post">
							<input type="text" asp-for="Id" hidden>
							<div class="row justify-content-center">
								<div class="col-md-6">
									<input type="text" asp-for="FirstName" placeholder="İsim">
								</div>
							</div>
							<div class="row justify-content-center">
								<div class="col-md-6">
									<input type="text" asp-for="LastName" placeholder="Soyisim">
								</div>
							</div>
							<div class="row justify-content-center">
								<div class="col-md-6">
									<input type="text" asp-for="Email" placeholder="Email *">
								</div>
							</div>
							<div class="row justify-content-center">
								<div class="col-md-6">
									<input type="date" asp-for="BirthOfDate" value="1990-01-01"
			 min="1900-01-01" max="2010-01-01" placeholder="Doğum Tarihi">
								</div>
							</div>

							<div class="row justify-content-center mb-5">
								<div class="col-md-6">
									<label for="city">İl Seçiniz</label>
									<select class="custom-select" id="cityR" asp-for="CityId">
									</select>
								</div>
							</div>
							<div class="row justify-content-center mb-5">
								<div class="col-md-6">
									<label for="county">İlçe Seçiniz</label>
									<select class="custom-select" id="countyR" asp-for="CountyId">
									</select>
								</div>
							</div>
							<div class="row justify-content-center">
								<div class="col-md-6">
									<textarea asp-for="Address" rows="2" placeholder="Adres"> </textarea>
								</div>
							</div>
							@if (Model.IsExpert)
							{
								<div class="row justify-content-center">
									<div class="col-md-6">
										<textarea asp-for="Description" rows="2" placeholder="Açıklama"> </textarea>
									</div>
								</div>
								<div class="row justify-content-center mb-5">
									<div class="col-md-6">
										<label for="category">Kategori Seçiniz</label>
										<select class="custom-select" id="categoryR" asp-for="CategoryIds" multiple>
										</select>
									</div>
								</div>
								<input type="checkbox" asp-for="IsExpert" hidden>
								@Html.ActionLink("Hizmet Taleplerim", "ExpertBids", "UserProfile", null, new { @class = "btn" })
								<button class="btn red-btn">Güncelle</button>
							}
							else
							{
								@Html.ActionLink("Hizmet Taleplerim", "UserBids", "UserProfile", null, new { @class = "btn" })
							<button class="btn red-btn">Güncelle</button>
							}
							

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- support-area-end -->
</main>
<script>
	$(document).ready(function () {
		$.ajax({
			url: window.location.origin + '/CategoryList/GetUserCityCountyAndCategoryId',
			type: 'GET',
			dataType: 'json',
			success: function (d) {
				let userId = d.userId;
				let userCityId = d.cityId;
				let userCountyId = d.countyId;
				let userCategoryIds = d.categoryIds;
				var city = $('#cityR');
				city.append($("<option></option>").val(0).html('Lütfen Şehir Seçiniz'));
				$.ajax({
					url: window.location.origin + '/CategoryList/GetCities',
					type: 'GET',
					dataType: 'json',
					success: function (d) {
						$.each(d, function (i, c) {
							if (c.id == userCityId) {
								city.append($("<option selected></option>").val(c.id).html(c.name));
							} else {
								city.append($("<option></option>").val(c.id).html(c.name));
							}
						});
						city.val(userCityId).change()
					},
					error: function () {
						alert('Error!');
					}
				});

				//county Bind By city id
				$("#cityR").change(function () {
					var cityId = userCityId ? userCityId : parseInt($(this).val());
					if (!isNaN(cityId)) {
						var county = $('#countyR');
						county.append($("<option></option>").val(0).html('Lütfen Bekleyin ...'));
						$.ajax({
							url: window.location.origin + '/CategoryList/GetCounties',
							type: 'GET',
							dataType: 'json',
							data: { cityId: cityId },
							success: function (d) {
								county.empty(); // Clear the plese wait
								county.append($("<option></option>").val(0).html('Lütfen İlçe Seçiniz'));
								$.each(d, function (i, c) {
									if (c.id == userCountyId) {
										county.append($("<option selected></option>").val(c.id).html(c.name));
									} else {
										county.append($("<option></option>").val(c.id).html(c.name));
									}
								});
							},
							error: function () {
								alert('Error!');
							}
						});
					}
				});

				var category = $('#categoryR');
				$.ajax({
					url: window.location.origin + '/CategoryList/GetCategories',
					type: 'GET',
					dataType: 'json',
					data: { userId: userId, },
					success: function (d) {
						$.each(d, function (i, c) {
							if (userCategoryIds.some(x => c.id == x)) {
								category.append($("<option selected></option>").val(c.id).html(c.name));
							} else {
								category.append($("<option></option>").val(c.id).html(c.name));
							}
						});
					},
					error: function () {
						alert('Error!');
					}
				});
			},
			error: function () {
				alert('Error!');
			}
		});


	});
</script>
<!-- main-area-end -->

InfotechLab.Web/Views/UserProfile/UserBids.cshtml
@model IList<InfotechLab.Entities.Bid>
@{
	Layout = "_Layout";
}
<div class="col">
	<aside class="blog-sidebar">
		<div class="widget mb-40">
			<div class="single-sidebar white-bg">
				<div class="sidebar-title mb-25">
					<h3>Teklifler</h3>
				</div>
				<div class="cat-list">
					<ul class="row d-flex">
						@foreach (var item in Model)
						{
							<li class="col-4 p-2" >
								<div class = "w-100 h-100" style="border: 1px solid black">

								<div class="row justify-content-center">
									<div class="col-md-6">
										@item.CreatedDate
									</div>
									@if (item.Price is not null)
									{
										<div class="col-md-6">
											@item.Price
										</div>
									}

								</div>
								<div class="row justify-content-center">
									<div class="col">
										@item.Description
									</div>
								</div>

								@if (@item.IsAccepted == false)
								{
									<div class="row justify-content-center">
										<div class="col-md-6">
											Teklif Beklemede
										</div>
									</div>
								}
								else
								{
									<div class="row justify-content-center">
										<div class="col-md-6">
											Teklif Kabul Edildi
										</div>
									</div>
								}
								@if (@item.Price is not null && @item.IsAccepted == false)
								{
									@Html.ActionLink("Kabul Et","AcceptBid","CategoryList", new {id = item.Id},new {@class = "btn red-btn"})
								}
					</div>
					</li>
						}
					</ul>
				</div>
			</div>
		</div>
	</aside>
</div>